"""empty message

Revision ID: 767011f4cd9c
Revises: 02c9f3080a03
Create Date: 2021-10-04 11:31:42.755484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767011f4cd9c'
down_revision = '02c9f3080a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('employee')
    op.create_unique_constraint(None, 'permission', ['permission_id'])
    op.create_unique_constraint(None, 'role', ['role_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'permission', type_='unique')
    op.create_table('employee',
    sa.Column('name', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.NUMERIC(precision=50, scale=0), autoincrement=False, nullable=False),
    sa.Column('salary', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('employee_id', name='employee_pkey')
    )
    op.create_table('books',
    sa.Column('bookTitle', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('bookText', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('bookTitle', name='books_pkey')
    )
    # ### end Alembic commands ###
